### ISSUE TITLE
Does Oxide-auth support other Mode like Implicit Grant or Client Credentials Grant except authorization code?

### ISSUE THREAD

**Issue by Jeeesie** [HeroicKatora/oxide-auth#102]
Does Oxide-auth support other Mode like Implicit Grant or Client Credentials Grant except authorization code?

**Comment by HeroicKatora** [comment]
No. It should be possible to add Client Credentials by combining the existing primitives though.

**Comment by Jeeesie** [comment]
Ok, Thanks.
