### ISSUE TITLE
Tracking issue for 0.5

### ISSUE THREAD

**Issue by Geobert** [HeroicKatora/oxide-auth#103]
Once the async work has landed, what are the next steps in order to stabilize 0.5?

Known interface deficiencies:

- [x] #68 
- [x] #108

**Comment by Geobert** [comment]
Now that `async` is merged, what do we need to have a 0.5 published on `crates.io`?

**Comment by HeroicKatora** [comment]
I'll cut another pre-release tonight and when I had time to ensure that I didn't overlook any interface changes that are compatibility risks then a full release of `0.5` and release notes etc. (this weekend, maybe).

**Comment by Geobert** [comment]
Thank you, I though there were more work planned to have a 0.5 live ready :)

**Comment by HeroicKatora** [comment]
There's probably one necessary more small change after the pre-release: Encapsulating the parameter to the solicitor to ensure forward compatibility with introducing some additional state information in a future minor release.

**Comment by Geobert** [comment]
Congratulation for 0.5! Didn't notice it was out 5 days ago already :D

**Comment by HeroicKatora** [comment]
Thanks, it literally wouldn't have been possible without You.

**Comment by Geobert** [comment]
> 
> 
> Thanks, it literally wouldn't have been possible without You.

You're welcome! We needed it and that's how Open Source works ;)
