### ISSUE TITLE
[Question] What's the expected behavior when post login called without starting a transaction?

### ISSUE THREAD

**Issue by Geobert** [HeroicKatora/oxide-auth#107]
Hi,

I'm in deep testing of my OAuth2 server at the moment, and there is some edge cases where I don't really know what the expected behavior:

I have `/authorize` endpoint to start a transaction, and serve a login form. This form POST to `/login`.

My test is about hitting `/login` without requesting `/authorize` first.

What's the expected behavior here? I though it would be rejected, but I'm redirected to `redirect_uri` with a `code`, like if everything was normal.

(sorry for the bad label, there's no "question" template to auto label as question)

**Comment by HeroicKatora** [comment]
The expected case is that You do some form of CSRFC-protection, such as one-time-tokens, here. While the mechanism for this is out-of-scope, you can find more considerations [in section 10.12](https://tools.ietf.org/html/rfc6749#section-10.12) and following. In particular it recommends _both_ the authorization server and client should roll protection mechanisms but is somewhat vague:

>    The authorization server MUST implement CSRF protection for its
   authorization endpoint and ensure that a malicious client cannot
   obtain authorization without the awareness and explicit consent of
   the resource owner.

I would personally suggest storing at least, on the server, in each user session the client,scope,time of the last served consent page and denying any solicitation that does not match this tuple, then invalidating it. If you think that this could be something the library may help with, feel free to suggest a scheme.

**Comment by HeroicKatora** [comment]
For the sake of completeness, don't forget setting more security settings such as: [Frame Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options), [CORP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy), [COOP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy) and [X-XSS-Protection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) with whatever method the chosen framework and software stacks allow to reduce your surface.

**Comment by Geobert** [comment]
Thank you very much for your insights! Very informative :)
