### ISSUE TITLE
Can this library be used to make an OAuth2 provider?

### ISSUE THREAD

**Issue by bbigras** [HeroicKatora/oxide-auth#142]
To implement /access_token, /authorize ....

**Comment by HeroicKatora** [comment]
That's the entire purpose, yes. Any ideas how to make this clearer? Where'd you discover the library that didn't answer this question?

**Comment by bbigras** [comment]
Sorry.

I saw oxide-auth mentioned on the Rust forum https://users.rust-lang.org/t/oauth-2-0-service-provider-in-rust/12875/4?u=bbigras.

I saw oxide-auth-axum at first and it seemed to be client.

**Comment by bbigras** [comment]
Is `oxide-auth-axum` fully usable yet?

`oxide-auth-axum` doesn't seem to have `Authorize` like `oxide_auth_actix` has.

**Comment by danielalvsaaker** [comment]
Yes, it is fully usable. It does not follow the actor model as the `actix` library does, so it is more comparable to the `rocket` implementation.
