### ISSUE TITLE
Gotham frontend

### ISSUE THREAD

**Issue by ParisLiakos** [HeroicKatora/oxide-auth#16]
Feature
=========

Gotham is probably the best solution for web development since iron, nickel are no longer actively maintained and rocket requires nightly.
We should build against 0.2 version, so postponing until its released.

--------

 - [x] A pull request (#18)

**Comment by HeroicKatora** [comment]
Another future based frontend, that sounds very nice. As a basic orientation, looking at the implementation of [`actix`](https://github.com/HeroicKatora/oxide-auth/blob/actix/src/frontends/actix.rs) may be of interest.

**Comment by ParisLiakos** [comment]
Thank you! The actix implementation helped a lot :+1: 
I will open a pull request soon for this, need to do some cleanup first.
