### ISSUE TITLE
[QUESTION] How to integrate `oxide_auth_async` and `oxide_auth_actix`?

### ISSUE THREAD

**Issue by FrancisMurillo** [HeroicKatora/oxide-auth#163]
# Feature

Currently trying to integrate `oxide_auth_async` with my `oxide_auth_actix` project so that calling async functions will be smoother. Following the example in the `oxide_auth_actix` crate, I have a problem within the `oxide_auth_actix::OAuthOperation` section were:

```
OAuthAction::AuthGet => {
  op.run(self.with_solicitor(AuthGetSolicitor))
},
```

The problem is that the `oxide_auth_async::endpoint::Endpoint` does not implement `oxide_auth::endpoint::Endpoint` which makes sense but prevents me from integrating the async endpoint. Is there another way or this is not possible at the moment? 

## Alternatives

I can still call async methods in non-async methods but it is a bit dirty which I would usually do:

```
let handle = tokio::runtime::Handle::current();
let _guard = handle.enter();

futures::executor::block_on(my_async_result_method())?;
```

## Context

Trying to convert my `oxide_auth_actix` project to support async functions for a cleaner code and perhaps for better performance.

## Tracking pull request

 - [ ] A pull request (does not yet exist/exists at #&#8230;)

**Comment by HeroicKatora** [comment]
You can fundamentally not (properly) use async functions without a runtime, and should avoid `block_on` in library code. Most of the traits are used for higher-level combinators, though. In particular the high-level combinators of which the respective `Endpoint` traits are an example just won't allow switching.

For further explanation of why sync and async are seggregated see, for instance, [this blog post](https://www.thecodedmessage.com/posts/async-colors/).

That said, *you* could create other high-level abstractions by accessing the underlying state machines directly, that is calling [`Authorization::advance`](https://docs.rs/oxide-auth/latest/oxide_auth/code_grant/authorization/struct.Authorization.html#method.advance) etc. There's no intermediate layer though.

**Comment by FrancisMurillo** [comment]
Agreed that `block_on` should be avoided. I do understand async functions require a runtime, so I was thinking it may be possible under the `actix` runtime. I was thinking that `oxide_auth_actix` could uses `oxide_auth_async` internally instead of `oxide_auth` maybe as a feature flag or something although this would be admittedly complicated or not possible.

Okay, I'll try to use the state machines directly.

**Comment by FrancisMurillo** [comment]
So what I did is rework `oxide-auth-actix` to use `oxide-auth-async` instead and it works now. I didn't need to use the state machines directly but used the flows instead.

**Comment by HeroicKatora** [comment]
Do you think your changes on `oxide-auth-actix` are enough to open up a PR? I'm interested and it sounds generally much more flexible than the current sync implementation.
