### ISSUE TITLE
Implement `oxide_auth_async::endpoint::Enpoint<_>` for `oxide_auth::frontends::simple::extensions::Extended`

### ISSUE THREAD

**Issue by Geobert** [HeroicKatora/oxide-auth#170]
# Feature

While trying to use PKCE, I hit the fact that `oxide_auth::frontends::simple::extensions::Extended` does not implement `oxide_auth_async::endpoint::Enpoint<_>` (note the `async`)

## Alternatives

No alternative that I know of

## Tracking pull request

I’m willing to do this on behalf of my company but I need to discuss which path we should take.

As far as I understand the code, I should be able to implement the needed trait in `oxide_auth_async`, shouldn’t I?

**Comment by Geobert** [comment]
Ok, not that simple as `inner` is private…

**Comment by Geobert** [comment]
I have an issue though: When in access token flow, `Pkce::verify` doesn’t receive `method` as parameter (it’s `None`)

**Comment by Geobert** [comment]
I don’t understand how the Extensions is supposed to go from AuthorizationFlow to AccessTokenFlow

**Comment by HeroicKatora** [comment]
Do you have in-progress code? Maybe I can have a look and debug where the information is lost, and how to rework that data flow.

**Comment by Geobert** [comment]
> Do you have in-progress code? Maybe I can have a look and debug where the information is lost, and how to rework that data flow.

I think I got it: I need to keep them in the login form to it is passed along ^^'

Are you alright with putting some field `pub` so we can implement the needed traits from oxide-auth-async?

(If yes, will be done in 2 weeks as I’m going in holidays today)

**Comment by HeroicKatora** [comment]
I seem to be unable to spot any new commits in the branch you've linked. Generally, having the pass them in the form is potentially the intended path? But then again other applications would require storing them into the _server side_ token. Is there a reference or specification relating to the use case you're looking to solve?

**Comment by Geobert** [comment]
I forgot to commit x) It’s done now :)
