### ISSUE TITLE
Missing release of `oxide-auth-actix`

### ISSUE THREAD

**Issue by ctron** [HeroicKatora/oxide-auth#187]
It looks like the `oxide-auth-actix` crate hasn't seen a release in the recent time (2 years ago). However, the examples are based on code that got added after the latest release (`0.2.0`):

https://github.com/HeroicKatora/oxide-auth/blob/17500834bf9f02f00794c210e8b8ae0f6e7781a8/oxide-auth-actix/src/lib.rs#L29

Is used here:

https://github.com/HeroicKatora/oxide-auth/blob/17500834bf9f02f00794c210e8b8ae0f6e7781a8/oxide-auth-actix/examples/actix-example/src/main.rs#L16

I thin it would make sense to have release of that crate, providing this version.

**Comment by ctron** [comment]
This would solve solve https://github.com/HeroicKatora/oxide-auth/issues/172 … as the version supporting `actix = "0.12"` was never published.

**Comment by HeroicKatora** [comment]
I think I'll need to build myself a dashboard with these, losing track of exactly which the source trees are published and which are not. Thanks for the reminder.
