### ISSUE TITLE
AddonList seems to be ignored for `client_credentials`

### ISSUE THREAD

**Issue by ctron** [HeroicKatora/oxide-auth#195]
# Bug report

It looks to me like the `AddonList` extension is not being called/processed for `client_credentials` flows.

The effects of this bug are &#8230;

## Reproduction

Relevant environment (http frontend library, OS, network setup?)

1. Create an addon list
2. Register an access_token addon using `push_access_token`
3. Wrap the endpoint using: `Extended::extend_with(inner, addons)`
4. Create an access token using a client_credentials flow

The code in `execute` is never called.

## Expected behaviour

I would expect the code to the called. But the `AddonList` doesn't implement `client_credentials` from the `Extension` trait.

Tracking pull request
--------

 - [x] A pull request (does not yet exist/exists at #194)

**Comment by ctron** [comment]
Thanks for the quick merge! If possible, could you make another release? That would be awesome!

**Comment by HeroicKatora** [comment]
@ctron Done, oxide-auth 0.6.1 and oxide-auth-async 0.2.1
