### ISSUE TITLE
Extensions::iter_private returns PublicExtensions?

### ISSUE THREAD

**Issue by hrbigelow** [HeroicKatora/oxide-auth#39]
# Bug report

In [this](https://github.com/HeroicKatora/oxide-auth/blob/9e546ce230fb7c207835dd7415a792ca358e4cd2/src/primitives/grant.rs#L139) code (below):
```
    /// Iterate of the public extensions whose presence and content is not secret.
    pub fn iter_public(&self) -> PublicExtensions {
        PublicExtensions(self.extensions.iter())
    }

    /// Iterate of the private extensions whose presence and content must not be revealed.
    pub fn iter_private(&self) -> PublicExtensions {
        PublicExtensions(self.extensions.iter())
    }
```
shouldn't it be `PrivateExtensions`?

**Comment by HeroicKatora** [comment]
Oh my. Yes. How did it take so long to actually get noticed? Well, at least the fix is straightfoward.

**Comment by hrbigelow** [comment]
No worries - I think writing a test suite for auth is really hard, given the multi-server nature of it.  The code is super clean in any case!

**Comment by hrbigelow** [comment]
I'm studying your code so I can better understand how OAuth works, (and also use it correctly to implement an email-based signup flow)

One other bug FYI:  "ephermal" should be "ephemeral" at src/primitives/generator.rs:129

**Comment by HeroicKatora** [comment]
@hrbigelow I even have the correct spelling [in issuer](https://github.com/HeroicKatora/oxide-auth/blob/f91df51aa4e18e94d262046051ea17367366ed29/src/primitives/issuer.rs#L181) :smile:

**Comment by HeroicKatora** [comment]
Appreciate all of the reviews and nits by the way.
