### ISSUE TITLE
Rocket frontend

### ISSUE THREAD

**Issue by HeroicKatora** [HeroicKatora/oxide-auth#4]
Feature
=========

A frontend for `rocket` should be built, complementing the existing one. It is the arguably biggest alternative to `iron`.

The basic structure should stay the same, a base configuration class constructing an opaque state model which can be used to get instances of `authorization`, `access_token` and `resource` handlers. Those can then be mounted to custom paths etc.

Instead of Plugins, rocket relies on `guards` which can also be queried dynamically on a request.

Tracking pull request
--------

 - [ ] A pull request does not yet exist

**Comment by HeroicKatora** [comment]
Since this project makes use of `ring`, it makes great sense to wait for Rocket and ring to resolve their current versioning troubles before tackling this feature.

**Comment by liuchong** [comment]
How is the status about this? :joy_cat:

**Comment by HeroicKatora** [comment]
Not actively worked on. The `ring` version giving us the freedom to link multiple versions hasn't happened yet, rocket is still nightly only.

The basic integration shouldn't be too different from rouille, after all it is just implementing a trait for the `HttpRequest´ and `HttpResponse`. But I'd like to integrate into rockets macros and especially guards as well since I would like to focus on idiomatic usage and decent interoperability.

Expect some work *after* 0.4 is released (targeted for mid to end of May) since the interface is currently being refactored to be more friendly to task/future/actor based approaches.

**Comment by HeroicKatora** [comment]
I plan to do it anyways for v0.4 (against rocket `0.4`), and expect to at least include some minimal bindings. Additional wrappers to provide an 'idiomatic' experience will then be added in later version as we gain some insight in necessary problems and solutions.
