### ISSUE TITLE
externalize session state

### ISSUE THREAD

**Issue by henris42** [HeroicKatora/oxide-auth#43]
Hi,

One major improvement I'd like to see is to have option to carry the authentication flow state in external database - my use case would use REDIS. The rationale for it is to support clustered environment with load balancer in front, with minimal intelligence in the network boxes.

I'd be happy to make a PR about this myself, if you are happy with the concept and can point me in right direction.

**Comment by HeroicKatora** [comment]
Coupling OAuth to a specific database and *requiring* a database seems fairly convoluted to me, this is intended to be library, not a framework. The flow should not require persistence itself, but maybe it could return more of its internal state for the cases of error and consent required? That could then be put into a database by the library user (aka. you).

I can probably give you some guidance if you outline your idea where you would intend to add this to the current architecture (as a primitive? in the `Endpoint` trait? somewhere in the `code_grant` backend?) more clearly. It's not yet clear to me what you intend to do in the end.

**Comment by henris42** [comment]
Yes, a complicated issue. I'd like to discuss with your direct if possible.

**Comment by HeroicKatora** [comment]
I don't have a lot of time I can spend on this project, at the moment. You're welcome to propose changes. But to do this, I either need: a concrete proposed change in the architecture; or many more details over your usecase and necessary functionality. In both scenarios I'd prefer Github or mail (see git commits) if you require some level of privacy but I don't see the point in a discussion with the level of detail you have provided until now, my information on your project is limited to vague intentions.

This may sound a bit assumptious but let me be clear: I will happily take the time reviewing PRs and offer suggestions but I'm not doing consulting for this project, at this time.

**Comment by henris42** [comment]
Thanks and no worries, we already made the demo we were looking for, integrating REDIS. It will take some time for us to decide what we should do on PR side.

**Comment by HeroicKatora** [comment]
Great to hear it worked!

**Comment by Jeeesie** [comment]
> Thanks and no worries, we already made the demo we were looking for, integrating REDIS. It will take some time for us to decide what we should do on PR side.

Can you share me the way you realize it ? or reference project?   We want to integrate REDIS too.  I will appreciate it .
