### ISSUE TITLE
implement CORS 

### ISSUE THREAD

**Issue by greenpdx** [HeroicKatora/oxide-auth#5]
I am trying to run a server that requires CORS. I am running the program   
cargo run --example authorization_code
with it listening to 0.0.0.0:8020.

Failed to load http://10.0.42.107:8020/auth/login: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

It uses OPTIONS method.

How do I add CORS?

**Comment by HeroicKatora** [comment]
It should be possible by adapting some of the code.

The example makes assumption of running under `localhost:8020` and `localhost:8021` respectively. Use of the example code for running on a remote server was therefore not intended. I'm a bit confused as I do not make any mention of the OPTIONS method in the example itself. Can you explain your setup a bit more in-depth? Which server is communicating with which client and where does the example run and how it accessed?

It might overall be better to not simply run the example but instead adapt it into your own software. This makes greater customization possible.

**Comment by greenpdx** [comment]
I am trying to do two things at once. I am using Vue as a front end framework. I have a website https://taxnvote.org that I want to add login and "stuff".  I have built a rust server using json-rpc, diesel, that uses JSON POSTs.  Here the code https://github.com/greenpdx/jrpc

I am now trying to create a login that uses oauth2 written in rust for the server.  I am working on the front end first so I just wanted a quick and dirty server for testing. 

I think I am going to have to work on the backend first. oauth is not as simple as I had hoped. It look like I am going to study more.

What is the API for oxide-auth? how would I integrate it into my server?

**Comment by HeroicKatora** [comment]
You could implement and use a custom `frontend`. The one provided right now is only available for `iron` as my time has been limited. Documentation for the `frontend` submodule can be found here: [documentation on docs.rs][frontend].

Specifically, you need to provide custom implementations of the `WebRequest`, `WebResponse` and `OwnerAuthorizer` traits in terms of your internal request data structure. Using those, you can then call the methods on `AccessFlow`, `AuthorizationFlow` and `GrantFlow` in reaction to a request. Just on more thing, always ensure to communicate over https even if it isn't enforced within the library as access tokens can be presented by anyone in their possession.

I'll treat this as a request for better documentation, specifically for implementing custom frontends.

[frontend]: https://docs.rs/oxide-auth/0.1.1/oxide_auth/code_grant/frontend/index.html

**Comment by greenpdx** [comment]
I have been trying to post oxide to json-rpc / hyper. Very long process.
What started this problem is I use Linux containers for development.  I have my rust container and my container for vue development. I then use my desktop browser to debug the code. That means I can not use localhost.   
I would really appreciate a how to add CORS. Just to get a working sample. It will help me understand how it works an my make it easier to port.
shaun

**Comment by HeroicKatora** [comment]
There is no CORS going on in the example. All content is served from the respective server and not shared between them.
