### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by HeroicKatora** [HeroicKatora/oxide-auth#64]
I would like to release the code under dual license: MIT OR Apache-2.0, instead of only MIT as is currently the case. This is more-or-less the default in the Rust community. As soon as all relevant parties agreed I'll create a pull request and update the documentation. This is in preparation to releasing the current preview as an actual version for the base crate and all servers.

cc: @ParisLiakos @asonix

If you consent to this change, then comment:

> I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by asonix** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ParisLiakos** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by HeroicKatora** [comment]
Thank you both for the quick response.
