### ISSUE TITLE
Tracking issue for `async`

### ISSUE THREAD

**Issue by HeroicKatora** [HeroicKatora/oxide-auth#70]
# Feature

One should be able to use the flows in an `async` context and have `async` primitives. This could be done by refactoring the `code_grant` flows into actual statemachines. It would be straightforward if it were possible to write this as a generic generator with inputs but having that in stable Rust will take quite some time, I fear. However there already exists a prototype for at least the `resource` process that show that it is possible.

## Alternatives

The `0.4` release series has a somewhat awkward wrapper implementation that uses a `PrimitiveError` and manual polling. This allows wrapping actors for all primitives and the futures one can create with message into a synchronous endpoint, and poll them as part of an opaque outer future. It's suboptimal at best.

It would also be possible to wrap the whole `code_grant` module with futures. Note however that this is infectious. Rust has no model of composable effectful programming. This would in essence require every user to use futures, instead of just those where the primitives are futures. Due to the standard implementation of futures it would also be suboptimal from a performance perspective by requiring some additional allocations for the future's creations and executor interaction.

## Context

The `actix` web-server is in the process of moving to well-supported standard futures. I'd expect some other to follow and want to eventually support `tide`.

## Tracking pull request

- [x] None yet.
- [x] Authorization Code Flow
- [x] Access Token Flow
- [x] Refresh Flow
- [x] Resource Flow

**Comment by Geobert** [comment]
Can this be closed then? Or do you have more things in mind?
