### ISSUE TITLE
Authentication via POST

### ISSUE THREAD

**Issue by thespooler** [HeroicKatora/oxide-auth#88]
I'm currently trying to figure out if it is possible to authenticate the user via POST request to the authorize endpoint. As it is now, it is not possible as the client_id, redirect_url and others are only validated in the authorization phase from `trait Request` in the request `query` (querystring). Is that mandated by a RFC?

Should the authorization of the user be done outside the authorize flow?
For the moment, the samples are pretty much a page with allow/deny, should that be considered a consent page and that the user should be already authenticated at this point by some other means?

I couldn't find the answer in the RFC, only
> If the request is valid,
> the authorization server authenticates the resource owner and obtains
> an authorization decision (by asking the resource owner or by
> establishing approval via other means)

Any thoughts?

**Comment by HeroicKatora** [comment]
> Should the authorization of the user be done outside the authorize flow?

Yes.
